name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      
    - uses: phish108/autotag-action@v1.1.55
      if: github.ref == 'refs/heads/main'
      with:
        github-token: ${{ secrets.PAT}}
        with-v: "true" 
        
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.PAT }}"
        tag_prefix: "v"   


# after deleting the tag v0.0.1
    
