name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: extract git commit
      uses: rlespinasse/git-commit-data-action@v1.x
    - name: update author
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
          base: main
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author:  ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          branch: "example-patches"
          delete-branch: true
          title: '[Example] Update report'
          token: ${{ secrets.PAT }}
         
          body: |
            Update report.
