name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "feature-main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3


    
