name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "feature-main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3


    - name: extract git commit
      uses: rlespinasse/git-commit-data-action@v1.x
    - name: update author
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
         
          branch: main
          delete-branch: false
          title: '[Example] Update report'
          token: ${{ secrets.PAT }}
         
          body: Update report..
            
          
