name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      
    - uses: phish108/autotag-action@v1.1.55
      if: github.ref == 'refs/heads/main'
      id: tag
      with:
        github-token: ${{ secrets.PAT}}
        with-v: "true" 
        
    - uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
       tag_name: 'v'
       release_name: 'Release v${{ steps.tag.outputs.stdout }}  '
       body: 'Description of the changes in this release'  
       
    - name: Build the Docker image
      run: echo ${{ steps.tag.outputs.stdout }}  

       


# after deleting the tag v0.0.1
    
