name: Java CI with Maven || Terraform 

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: extract git commit
      uses: rlespinasse/git-commit-data-action@v1.x
    - name: update author
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      
   
